# Do not background to ensure resources loaded before proceding
[[ -f $HOME/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

urxvtd -q -f -o &
xcompmgr -r4.2 -o.55 -c -l-5 -t-5 -c &
xwrits typetime=8:00 breaktime=0:30 +mouse +multiscreen +clock +top mono &
i3
