local vim = vim
local Plug = vim.fn['plug#']

vim.call('plug#begin')

Plug('cespare/vim-toml')
Plug('chrisbra/matchit')
Plug('dense-analysis/ale')
Plug('dense-analysis/neural')
Plug('EdenEast/nightfox.nvim')
Plug('hashivim/vim-terraform')
Plug('isobit/vim-caddyfile')
Plug('junegunn/fzf')
Plug('junegunn/fzf.vim')
Plug('junegunn/goyo.vim')
Plug('kaarmu/typst.vim')
Plug('leafgarland/typescript-vim')
Plug('NLKNguyen/papercolor-theme')
Plug('PhilT/vim-fsharp')
Plug('preservim/nerdtree')
Plug('preservim/nerdtree')
Plug('purescript-contrib/purescript-vim')
Plug('rhysd/committia.vim')
Plug('rizzatti/dash.vim')
Plug('shinglyu/vim-codespell')
Plug('tpope/vim-commentary')
Plug('tpope/vim-fugitive')
Plug('tpope/vim-git')
Plug('tpope/vim-markdown')
Plug('tpope/vim-rhubarb')
Plug('tpope/vim-surround')
Plug('tpope/vim-vinegar')

vim.call('plug#end')
