# Ensure unique manpath, path items
typeset -U MANPATH manpath PATH path

# General
export EDITOR="vim"
export LANG="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export MAILDIR="${HOME}/Maildir"
export PAGER="less -R"

# My bin utils
path=(~/bin $path)

# NPM
NPM_PACKAGES=${HOME}/.npm-packages
path=(${NPM_PACKAGES}/bin $path)
manpath=(${NPM_PACKAGES}/share/man $manpath)

# FZF
#export FZF_DEFAULT_COMMAND='ag --files --hidden --follow --glob "!.git/*"'
#export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden'
