export EDITOR="vim"
export MAILDIR="${HOME}/Maildir"
export PAGER="less -R"

# virtualenvwrapper
export WORKON_HOME=~/envs

# GNUPG
#eval `gpg-agent --daemon`
#
#if [ -f "${HOME}/.gpg-agent-info" ]; then
#      . "${HOME}/.gpg-agent-info"
#      export GPG_AGENT_INFO
#      export SSH_AUTH_SOCK
#      export SSH_AGENT_PID
#fi
#
#export GPG_TTY=`tty`

# Pelican
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# MacPorts
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"

# MacPorts postgres
export PATH="/opt/local/lib/postgresql94/bin:$PATH"

# MacPorts mysql
export PATH="/opt/local/lib/mysql51/bin:$PATH"

# Packer
export PATH="${HOME}/packer:$PATH"
