##
## PARAMETERS (zshparam)
##

HISTFILE=~/.zhistory
HISTSIZE=4096
SAVEHIST=2048

##
## OPTIONS (zshoptions)
##

# Changing directories
setopt AUTO_CD
setopt CDABLE_VARS
setopt CD_SILENT

# Expansion and Globbing
setopt EXTENDED_GLOB

# History
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS
setopt HIST_SAVE_NO_DUPS
setopt HIST_VERIFY
setopt SHARE_HISTORY

# Command prompt
setopt PROMPT_SUBST

# Include git branch name in prompt
autoload -Uz vcs_info
precmd_functions+=( vcs_info )
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git:*' formats '[%b]%m'
zstyle ':vcs_info:git:*' actionformats '[%b|%a]'

PROMPT='%n@%m:%~/ %F{32}${vcs_info_msg_0_}%f> '

##
## Completion
##

autoload -Uz compinit
compinit

# Zle
unsetopt BEEP

##
## ZLE (zshzle)
##

# Vi editing
bindkey -v

bindkey '^[m' copy-prev-shell-word # File rename magick
bindkey '^r' history-incremental-search-backward

bindkey -M viins "^[[1~" vi-beginning-of-line   # Home
bindkey -M viins "^[[4~" vi-end-of-line         # End
bindkey -M viins '^[[2~' beep                   # Insert
bindkey -M viins '^[[3~' delete-char            # Del
bindkey -M viins '^[[5~' vi-backward-blank-word # Page Up
bindkey -M viins '^[[6~' vi-forward-blank-word  # Page Down

##
## Aliases
##

alias cp='nocorrect cp -v -i'
alias mkdir='nocorrect mkdir -v'
alias mv='nocorrect mv -v -i'
alias rm='nocorrect rm -v -i'

alias bc='bc -l'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias ssh='TERM=xterm-color ssh'
alias view='vim -N -R'
alias vim='vim -N'

alias rg='rg --smart-case'
alias pgpp='pgpp --semicolon-after-last-statement --preserve-comments'

##
## Named directories
##

hash -d dotfiles=~/Projects/dotfiles

# ls
case $(uname -s) in
'Darwin'| 'FreeBSD')
    export LSCOLORS=exfxcxdxbxegedabagacad
    alias ls='ls -F -G'
    ;;
'Linux')
    alias ls='ls -F --color=auto'
    eval "$(dircolors ~/.dircolors)"
    ;;
esac

alias l.='ls -d .[^.]*'
alias ll.='ls -l -d .[^.]*'
alias ll='ls -l'
alias lsd='ls -ld *(-/DN)'

# Python virtualenv
alias venv='python3.11 -m venv .venv && . ./.venv/bin/activate && pip install --upgrade pip -q'
alias venv39='python3.9 -m venv .venv && . ./.venv/bin/activate && pip install --upgrade pip -q'

# My logbook
function lb() {
    local lbdir=~/logbook
    [[ ! -d $lbdir ]] && mkdir $lbdir
    vim "$lbdir/$(date '+%Y')/$(date '+%Yw%V').md"
}

gsw() {
  git switch "$(git branch --list --all | sed -e '/^*/d' -e 's/^  //' | fzf)"
}

# export ZVENV_TRUSTED_VENVS=(
#     "/Users/emiel/Projects/blog/venv"
#     "/Users/emiel/Projects/django-lifecycle/venv"
#     "/Users/emiel/Projects/distributor-portal-service/.venv"
#     "/Users/emiel/Projects/gonos/src/.venv"
#     "/Users/emiel/Projects/tiqets-auth/.venv"
#     "/Users/emiel/Projects/tiqets-backoffice/.venv"
#     "/Users/emiel/Projects/tiqets-sql/.venv"
#     "/Users/emiel/Projects/tiqetsweb/.venv"
# )
# source "${HOME}/Projects/zsh-venv/zsh-venv.zsh"

# saml2aws completion
eval "$(saml2aws --completion-script-zsh)"

# kubectl completion
eval "$(kubectl completion zsh)"

# direnv
eval "$(direnv hook zsh)"

[[ -f ~/.config/zsh/tiqets.zsh ]] && source ~/.config/zsh/tiqets.zsh
